### ISSUE TITLE
YDS API configuration issues

### ISSUE THREAD

**Issue by vafopoulos** [YourDataStories/ontology#23]
Resolve issues reported here https://docs.google.com/document/d/1On7I3d4dbpiHWJRLKP75atkIdusvIIvePpILOHRLft4/edit#heading=h.wplc1ts9kavn

**Comment by giorgosvaf** [comment]
I have made some comments on this document. Almost everything have been resolved except from issue with the triplet below,
http://linkedeconomy.org/resource/Contract/4Α81ΟΡ1Θ-ΓΜΨ pc:kind ?o

Please check the comments for more information.
