### ISSUE TITLE
T-Box (skos:Concepts) in OWL files

### ISSUE THREAD

**Issue by vafopoulos** [YourDataStories/ontology#26]
Modify OWL accordingly.

**Comment by giorgosvaf** [comment]
The appropriate changes are made and you can find them here,
https://github.com/YourDataStories/ontology/blob/master/Overall%20model/YDS%20model.owl

Also, each class and property includes a label or comment in order to make them more human-friendly.

**Comment by vafopoulos** [comment]
@Polymathronic please review if you are ok with them
