### ISSUE TITLE
Wrong type for addresses

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/ontology#27]
The addresses should be typed as vcard:Address, but are declared as instances of elod:Subsidy:

```
PREFIX vcard2006: <http://www.w3.org/2006/vcard/ns#>

SELECT DISTINCT ?address ?p ?o
FROM <http://yourdatastories.eu/NSRF/Diavgeia>
WHERE {
  ?organization vcard2006:hasAddress ?address .
  ?address ?p ?o.
}
```

**Comment by giorgosvaf** [comment]
The issue is resolved. The addresses are declared as instances of vcard:Address now.

Please check the above query again to see the related change.

**Comment by Polymathronic** [comment]
Can you please re-upload the data? According to Panagiotis, we had to revert to a four day old backup due to a server crash.

**Comment by giorgosvaf** [comment]
ok i will inform you as soon as we are ready.

**Comment by giorgosvaf** [comment]
We have made the update of pilot 1 data.
