### ISSUE TITLE
YDS Overall OWL file

### ISSUE THREAD

**Issue by giorgosvaf** [YourDataStories/ontology#32]
I can not open with protege the following OWL file,
https://github.com/YourDataStories/ontology/blob/master/Overall%20model/YDS%20model.owl

At first the error was the duplicate prefix declaration(see prefix geo in lines 28 &37) but i fixed that.

And then another error was appeared: Line 2386 "Cannot answer characters when object properties are excepted"

Please check the OWL file by opening it at Protege at first, and then proceed to update it on Github.

**Comment by Polymathronic** [comment]
Should be fixed now.

**Comment by giorgosvaf** [comment]
Yes it's ok thanks!

Please also check the following issue which is related to OWL file.

https://github.com/YourDataStories/ontology/issues/30
