### ISSUE TITLE
gr:name vs foaf:name

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/ontology#34]
I see that `gr:name` has a cardinality restriction (0..1). We might have agents with multiple names (or in multiple languages). `foaf:name` doesn't have this limitation. Perhaps we should switch.

**Comment by giorgosvaf** [comment]
You are right about this, but i don't think that this is a high priority right now.

Even if we make this change, i would suggest to do it in the next version of our data model.

What is your opinion on this?

**Comment by Polymathronic** [comment]
We can switch whenever you are ready. Either way, this decision will not have an immediate effect on the data, as we still don't have agents with multiple names.

**Comment by giorgosvaf** [comment]
i would suggest to keep both of them, just to add foaf:name.

what do you say?

**Comment by Polymathronic** [comment]
I can't say it's entirely wrong, but it would be difficult to justify the presence of two almost identical properties in one model. :/ We can also not do it, and limit the model to only one agent name.

**Comment by Polymathronic** [comment]
@vafopoulos What did we decide in the end?

**Comment by giorgosvaf** [comment]
@Polymathronic we decided to switch to foaf:name which do not have the limitation you referred to.
The reason is that we already have agents with multiple names in TED.
We'll use it also in pilot 1.
