### ISSUE TITLE
elod:financialYear range

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/ontology#35]
The range for `elod:financialYear` is [`xsd:gYear`](http://books.xmlschemata.org/relaxng/ch19-77127.html). Some values in pilot 1 appear malformed (e.g. years for committed items). Preferred format is YYYY.

**Comment by giorgosvaf** [comment]
Please could you be more specific on this because i can not see anything wrong with the format.

See the following query,

select distinct ?o 
from <http://yourdatastories.eu/NSRF/Diavgeia> 
where {
?s a elod:CommittedItem ; elod:financialYear ?o
}

**Comment by Polymathronic** [comment]
Actually, YASGUI returns the values as e.g. `"2015-01-01"^^xsd:gYear`, yet the HTML view of the result set returned by Virtuoso looks OK, so I thought I should have a closer look at what is really happening.

If you pick any other result type, you will notice the format actually corresponds to `xsd:date`. I believe it is an internal Virtuoso representation of the years (which is wrong). We could report it, but I'm thinking there's probably a good reason why they represent it that way.

**Comment by Polymathronic** [comment]
It has already been reported more than two years ago. :/

https://github.com/openlink/virtuoso-opensource/issues/125
