### ISSUE TITLE
Virtuoso Connection through JDBC and JENA

### ISSUE THREAD

**Issue by giorgosvaf** [YourDataStories/ontology#36]
I gave it another try and i can not make insertions of triples in Virtuoso.

See the following output,
virtuoso.jdbc4.VirtuosoException: Connection failed: Operation timed out

**Comment by Polymathronic** [comment]
How are you trying to connect? UV connects via `jdbc:virtuoso://<dev server ip>:1111/charset=UTF-8/` (with the appropriate credentials, of course).

**Comment by giorgosvaf** [comment]
I'm doing this,
jdbc:virtuoso://<server ip>/:1111/autoReconnect=true/charset=UTF-8/log_enable=2

I also tried excactly how you wrote it above but still the same error.

**Comment by arekstasiewicz** [comment]
Just a guess: try `jdbc:virtuoso:///:1111/autoReconnect=true/charset=UTF-8/log_enable=2`
( use `//` instead `///`)

**Comment by giorgosvaf** [comment]
i am using two, maybe i put the third one by mistake.

**Comment by Polymathronic** [comment]
How do you provide the access credentials for the connection?

**Comment by giorgosvaf** [comment]
connectionString = jdbc:virtuoso://<IP-server>/:1111/autoReconnect=true/charset=UTF-8/log_enable=2
username = "xxxxxx"
password = "xxxxxxxxxx"
graph = "http://....."

VirtGraph graph = new VirtGraph(graph,
                connectionString, username, password)

**Comment by Polymathronic** [comment]
Is this still an issue?

**Comment by giorgosvaf** [comment]
Yes it is!
@Polymathronic , do you have the same problem if you try a connection or not?

**Comment by Polymathronic** [comment]
We don't use Jena; UnifiedViews connects via JDBC without problems, though.

**Comment by Polymathronic** [comment]
I believe the port (1111) is blocked. I've just tried to connect with Jena from my local machine, and it didn't go through. UnifiedViews doesn't have that problem, because it's on the same machine.

**Comment by Polymathronic** [comment]
The port is now open. @giorgosvaf Could you please check if your problem is solved?

**Comment by giorgosvaf** [comment]
@Polymathronic thanks, it works!
