### ISSUE TITLE
elod:currencyIsoCode vs elod:countryIsoCode

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/ontology#37]
`elod:currencyIsoCode` is a datatype property, whereas `elod:countryIsoCode` is an object property. The former is also redundant as all currencies are provided as part of the currency taxonomy, and the corresponding codes via the `skos:notation` property.

**Comment by Polymathronic** [comment]
Also, what is the difference between `elod:currencyIsoCode` and `elod:currencyId`? I suggest we deprecate both.

**Comment by giorgosvaf** [comment]
I made the appropriate changes and we don't use these properties any more.
