### ISSUE TITLE
Pilot 3 documentation: Input data

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/ontology#39]
Please provide an example of the pilot 3 input data. Feel free to use the documents provided by pilots 1 and 2 as examples.

**Comment by Islhas** [comment]
An example of the input data has been uploaded to the github repository, pilot 3 branch as requested:  
https://github.com/YourDataStories/ontology/blob/pilot3/pilot3/inputdata_exp.md

**Comment by arekstasiewicz** [comment]
@Polymathronic could you please verify the sample and close the issue?
