### ISSUE TITLE
Pilot 3 documentation: Output data

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/ontology#40]
Please provide examples of the pilot 3 output (RDF) data. Make sure the graph you provide is extensive and covers all possible classes and properties. Providing multiple graphs to describe different types of resources is also recommended. Feel free to use the documents provided by pilots 1 and 2 as examples.

**Comment by niallob** [comment]
Yes. We are working on this.

**Comment by Islhas** [comment]
An example of the output RDF has been uploaded to the github repository, pilot 3 branch as requested:  
https://github.com/YourDataStories/ontology/blob/pilot3/pilot3/outputdata_exp.md

**Comment by giorgosvaf** [comment]
Please check the Properties elod:documentUrl, vcard:street-address, vcard:country-name, elod:contractId, elod:documentType which should have xsd:string as rdfs:range 

See the document, https://docs.google.com/spreadsheets/d/1xMiTAk7mXhGPnSU4-qspiYaN15ur4v3J0lU8qYODtzk/edit#gid=481927591.
