### ISSUE TITLE
Pilot 3 documentation: OWL specification

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/ontology#41]
Please provide an OWL specification of the pilot 3 data model. Make sure you provide the corresponding labels and comments for both classes and properties, as well as the domains and ranges for your predicates. Feel free to use the documents provided by pilots 1 and 2 as examples.

**Comment by Islhas** [comment]
The ontology specification has been uploaded to the github repository, pilot 3 branch as requested:  
https://github.com/YourDataStories/ontology/blob/pilot3/pilot3/Pilot3-OntologySpecification.docx

**Comment by arekstasiewicz** [comment]
@Polymathronic could you please verify the specification and close the issue?

**Comment by Polymathronic** [comment]
- _Contraction_ > _Contracting_
- You have 4 `elod:Currency` entries in the second table instead of two.
