### ISSUE TITLE
Pilot 3 documentation: Separate branch

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/ontology#43]
Please create a separate branch for the pilot 3 documentation (issue a pull request once everything is in place).

**Comment by Islhas** [comment]
A new branch for pilot 3 has been created and including the related documents as requested.
https://github.com/YourDataStories/ontology/tree/pilot3

**Comment by arekstasiewicz** [comment]
@Polymathronic could you please verify the changes and close the issue?
