### ISSUE TITLE
Pilot 1 and 3 data connections 

### ISSUE THREAD

**Issue by vafopoulos** [YourDataStories/ontology#46]
It seems that the following are potential interconnections:
- CPV (check [queries](https://github.com/YourDataStories/ontology/blob/master/Overall%20model/SPARQL%20queries.md#q2-cpv-codes-from-decisions-of-nsrf-projects) and [their results for pilot 1](https://docs.google.com/spreadsheets/d/1pbxI1_ScQhLCAavwFg68RLxhAs0QNHpyOx9SKb5Wm54/edit#gid=468360997).
- OECD CRS Code ([Queries](https://github.com/YourDataStories/ontology/blob/master/Overall%20model/SPARQL%20queries.md#q3-oecd-crs-code-of-nsrf-projects) and [results](https://docs.google.com/spreadsheets/d/1pbxI1_ScQhLCAavwFg68RLxhAs0QNHpyOx9SKb5Wm54/edit#gid=80138440)).
- contract/project location (in city level - @giorgosvaf  will provide more information)
- organisations (Buyers) (@giorgosvaf  will provide more information)

**Comment by niallob** [comment]
In the platform we will need a search by CPV code. This will require users to be presented with the text associated with a CPV code and not have to type in the number itself.
We also need to provide a common methodology for links to Eurostat, DBpedia etc.
Example requirement: A graph showing the total value of roads projects for 2014 in each EU member state as a percentage of GDP.

**Comment by Polymathronic** [comment]
@vafopoulos I don't think there are any OECD CRS codes in the pilot 3 graph.

@niallob With respect to the CPV code labels, please see: https://github.com/YourDataStories/ontology/issues/45#issuecomment-205938403 

As for linking to Eurostat, DBpedia etc. this was already discussed via the mailing list, and has nothing to do with the data model. If you think there is a need, you can open a separate issue (I would do it via Redmine, though).

**Comment by vafopoulos** [comment]
@Polymathronic  I know about  OECD CRS codes, but can be added manually or automatically
