### ISSUE TITLE
elod:issueDate does not exist in elod vocabulary

### ISSUE THREAD

**Issue by giorgosvaf** [YourDataStories/ontology#47]
You use elod:issueDate property which does not exist in elod vocabulary, you could use dcterms:issued instead of that.

select distinct \* 
from http://yourdatastories.eu/pilot3 
where {
?s elod:issueDate ?p
}

**Comment by mogaio** [comment]
It's included in Deliverable 3.3 as part of the elod vocabulary but we can fix that for sure.

**Comment by giorgosvaf** [comment]
Yes Please!

About elod vocabulary please check the following document,

https://docs.google.com/spreadsheets/d/1xMiTAk7mXhGPnSU4-qspiYaN15ur4v3J0lU8qYODtzk/edit#gid=481927591

**Comment by mogaio** [comment]
This issue is now fixed in the latest version of the rdf data.
