### ISSUE TITLE
Modeling Contracts pc:actualPrice, pc:agreedPrice and pc:estimatedPrice

### ISSUE THREAD

**Issue by giorgosvaf** [YourDataStories/ontology#48]
In the following document (sheet DataModel) you use the properties pc:actualPrice, pc:agreedPrice and pc:estimatedPrice, but you have made the mapping with two metadata values.

https://docs.google.com/spreadsheets/d/14YkWa6_PM8BtfnoWGQmMZacYIwmvfkdqKG6fzML0dic/edit#gid=1232340869

For example you use both pc:actualPrice & pc:estimatedPrice for "contract_initial_value_cost_eur" metadata value.
So first of all you have to make the correct mapping to metadata.

But, the data you retrieve are Tenders actually, so you can use just pc:estimatedPrice, because according to public contracts specification for Tenders this is the most appropriate property.

**Comment by mogaio** [comment]
We fixed this issue in the mapping spreadsheet and in our model so the "contract_initial_value_cost_eur" is mapped only by pc:estimatedPrice

**Comment by Polymathronic** [comment]
Related: https://github.com/YourDataStories/harvesters/issues/16

**Comment by Islhas** [comment]
Currently we mapped contract_initial_value_cost_eur to the pc:estimatedPrice and the contract_contract_value_cost_eur to pc:agreedPrice as agreed.

**Comment by arekstasiewicz** [comment]
@giorgosvaf could you please verify the changes?

**Comment by giorgosvaf** [comment]
Please provide metadata of a specific contract and the respective SPARQL query from your pilot 3 graph in order to verify the mapping.
