### ISSUE TITLE
CPV code labels

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/ontology#54]
We currently use `elod:cpvGreekSubject` and `elod:cpvEnglishSubject` for labels.
Proposal: Use `skos:prefLabel` and **language tags** to be in line with the modeling of other codes in the graph and the LOD best practices.

**Comment by giorgosvaf** [comment]
We proceed to skos concept implementation as we have discussed.
Please check the following query from pilot 1 graph,

select distinct \* 
from <http://yourdatastories.eu/NSRF/Diavgeia> 
where {
?cpv a elod:CPV ; skos:inScheme ?conceptScheme ; 
skos:notation ?cpvCode ; skos:prefLabel ?cpvName
} 

@Polymathronic a couple of questions,
1. Do we have to remove "elod" datatype properties of elod:CPV Class?
2. Should we pass the above to the common graph?
3. Pilot 3 should do the same for their data, right?

**Comment by arekstasiewicz** [comment]
@Polymathronic could you please provide the answer for the questions above and clarify the tasks for pilot3?

**Comment by Polymathronic** [comment]
1. If you have apps/users relying on those properties, then you could just [deprecate them](https://www.w3.org/TR/owl-ref/#Deprecation).
2. The common graph needs to be updated to reflect any changes in the data.
3. @arekstasiewicz There should be only one CPV code list, containing **all** CPV codes (in the taxonomies graph + a copy in the common graph for the JSON API). The changes should be applied there, and the URIs (which are reusable) would remain the same, so this discussion shouldn't affect the pilot 3 modeling choices.

**Comment by giorgosvaf** [comment]
So you are saying that we have to pass the whole information of CPV code list in Taxonomies & common graph, and obviously we don't need to have this information in pilot 1 or 3 graphs, but just the connection of the resources(for example among contract resource and CPV resource).

**Comment by Polymathronic** [comment]
@giorgosvaf Exactly. Linked Data is all about references (_"define once, reuse everywhere"_).

**Comment by giorgosvaf** [comment]
Yes sure! When i made this question i didn't know if we are fine and we are going to pass the whole information of CPV into taxonomies graph.
Thanks!

**Comment by giorgosvaf** [comment]
@Polymathronic I passed the whole information of CPV code list in Taxonomies & common graph.

Please check the following query in dev graph and let me know if we need anything else.

select distinct \* 
from <http://yourdatastories.eu/taxonomies> 
where {
<http://linkedeconomy.org/resource/CPV/03100000-2> ?p ?o
}
