### ISSUE TITLE
Data graph versioning

### ISSUE THREAD

**Issue by vafopoulos** [YourDataStories/ontology#55]
How to model and implement data graph update and versions. How to use DCAT.

**Comment by Polymathronic** [comment]
At dcat:Dataset level, we can use `owl:versionInfo` (for basic version information) and `adms:versionNotes` (for notes about changes with respect to previous versions):

```
owl:versionInfo “v 1.2” ;
adms:versionNotes “Fixed commodity codes” ;
```
