### ISSUE TITLE
DCAT-AP for all datasets.

### ISSUE THREAD

**Issue by vafopoulos** [YourDataStories/ontology#56]
Must be submitted by @giorgosvaf  for Pilot 1, from @Polymathronic  for pilot 2 and from @niallob  for pilot 3. Will be reviewed by @Polymathronic .
Draft specs here https://docs.google.com/document/d/1NF9ENEyd_qXIgqCIWn2GRLr7hPLA1UVIuyEOXN8E8BQ/edit

**Comment by Islhas** [comment]
For pilot 3, we updated the google docs file with the DCAT specs for pilot 3, you can find it uploaded to the pilot3 branch on the repository: 
https://github.com/YourDataStories/ontology/blob/pilot3/pilot3/dcat.md

**Comment by arekstasiewicz** [comment]
@vafopoulos could you please verify that this is complete for pilot3?

**Comment by giorgosvaf** [comment]
I think you should check the following,
1. The URI that describes your dataset, it would be better if it was something like <http://linkedeconomy.org/resource/Dataset/TED>
2. I think you could add more information about your dataset description via dct:description
3. Also you could add,
   dcat:contactPoint <http://linkedeconomy.org/resource/Organization/YourDataStories> ;

Please also see pilot 2 recommendation below,

<http://linkedeconomy.org/resource/Dataset/ODA-NL>
a dcat:Dataset ;
dct:title “Official Development Assistance (ODA) of the Netherlands” ;
dct:description “Official development assistance (ODA) is a term coined by the Development Assistance Committee (DAC) of the Organisation for Economic Co-operation and Development (OECD) to measure aid. It is widely used as an indicator of international aid flow. The data set covers Dutch government funded ODA activities in developing countries worldwide`.” ;
dct:publisher <http://linkedeconomy.org/resource/Organization/YourDataStories> ;
dcat:distribution [
            a dcat:Distribution ;
dct:description “The YourDataStories (YDS) SPARQL endpoint provides access to all YDS datasets. The ODA dataset is represented in the form of the http://yourdatastories.eu/data/ODA graph.” ;
dct:license [
            a dct:LicenseDocument ;
    rdfs:label “IATI Standard (http://iatistandard.org/)” ;
rdfs:comment “Copyright © Development Initiatives, on behalf of the IATI Secretariat Released under the Creative Commons attribution license http://creativecommons.org/licenses/by/4.0/” ;
] ;
dcat:accessURL <http://143.233.226.61:8890/sparq> ;
dct:format <http://publications.europa.eu/resource/authority/file-type/SPARQLQ> ;
dct:modified "2015-12-22T11:01:31+0000" ;
] ;
dcat:keyword “ODA”, “development”, “public spending”, “Netherlands” ;
dcat:contactPoint <http://linkedeconomy.org/resource/Organization/YourDataStories> ;
dct:theme [
            a skos:Concept;
] .

**Comment by giorgosvaf** [comment]
Sorry, I changed number 2 as follows,
1. I think you could add more information about your dataset description via **dct:description**

**Comment by Polymathronic** [comment]
@giorgosvaf I will add the WDI description. Can you please do the same for TED?

**Comment by giorgosvaf** [comment]
@Polymathronic I added the description in the related google document.
Do you need anything else?

**Comment by Polymathronic** [comment]
That's all @giorgosvaf. Thanks!
