### ISSUE TITLE
Usage of pc:kind

### ISSUE THREAD

**Issue by Polymathronic** [YourDataStories/ontology#60]
It appears the `pc:kind` property has a restriction on the code list to be used:

```
pc:kind rdfs:range skos:Concept, [
    a owl:Restriction ;
    owl:onProperty skos:inScheme ;
    owl:hasValue kinds:
  ]  .
```

In other words, the range is any skos:Concept from the [kinds](http://purl.org/procurement/public-contracts-kinds#) concept scheme. In pilots 1 and 3 we use our own concept schemes.

**Comment by giorgosvaf** [comment]
@Polymathronic, it is fixed!

Please check the following query,

select distinct ?kind 
from http://yourdatastories.eu/Diavgeia 
where {
?s pc:kind ?kind
}
